### ISSUE TITLE
[Feature Request] Add ability to disable options globally

### ISSUE THREAD

**Issue by amogusussy** [tchx84/Flatseal#553] opened 2023-07-30 14:21 UTC
In the 'All Applications', there should be an option to remove permissions to certain options.

For example, I don't want any apps to be give the `filesystem=host` flag. There should be an extra button that people can press that will disable it globally, so even if the application enables it by default, it will be overwritten.

**Comment by rusty-snake** [comment] 2023-07-30 16:38
Duplicate of #470

**Comment by rusty-snake** [comment] 2023-07-30 16:40
And #551

**Closed as not planned** 2023-08-21 01:37 UTC
